# Generated by Django 5.1.3 on 2024-12-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_article_tag_article_category_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название строки')),
                ('row_type', models.CharField(choices=[('latest', 'Последние добавленные'), ('category', 'Категория')], default='latest', max_length=50, verbose_name='Тип строки')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию, если тип строки — Категория.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Конфигурация строки',
                'verbose_name_plural': 'Конфигурации строк',
            },
        ),
    ]
