# Generated by Django 5.1.3 on 2024-12-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rowconfiguration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RowConfiguration',
        ),
    ]
