# Generated by Django 5.1.4 on 2024-12-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_count', models.IntegerField(choices=[(3, '3 карточки в строку'), (4, '4 карточки в строку'), (5, '5 карточек в строку')], default=5, verbose_name='Количество карточек в строку')),
            ],
            options={
                'verbose_name': 'Настройка сетки',
                'verbose_name_plural': 'Настройки сетки',
            },
        ),
    ]
