# Generated by Django 5.1.4 on 2024-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_gridsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridsettings',
            name='card_count',
            field=models.IntegerField(choices=[(3, '3 карточки в строку'), (4, '4 карточки в строку'), (5, '5 карточек в строку'), (6, '6 карточек в строку')], default=5, verbose_name='Количество карточек в строку'),
        ),
    ]
