# Generated by Django 5.1.4 on 2024-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_gridsettings_card_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='gridsettings',
            name='show_footer',
            field=models.BooleanField(default=True, verbose_name='Показывать подвал (footer)'),
        ),
        migrations.AddField(
            model_name='gridsettings',
            name='show_header',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку (header)'),
        ),
    ]
