# Generated by Django 5.1.4 on 2024-12-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_displaysettings_remove_gridsettings_show_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCategoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(choices=[('recent', 'Последние добавленные'), ('popular', 'Популярные'), ('category', 'Категория')], max_length=20, verbose_name='Тип отображения')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория (если выбрана)')),
            ],
            options={
                'verbose_name': 'Отображение категорий',
                'verbose_name_plural': 'Отображение категорий',
                'ordering': ['position'],
            },
        ),
    ]
