# Generated by Django 5.0 on 2024-12-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_article_content_markdown_article_editor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content_markdown',
        ),
        migrations.RemoveField(
            model_name='article',
            name='editor_type',
        ),
    ]
